# Bot by work of Steve Winton (@swinton) and John Bohannon (@imjohnbo)
# Source at: https://github.com/imjohnbo/issue-bot  
# Bot written in Java see index.js

name: Weekly Team Sync
on:
  schedule:
    - cron: 5 * * * *

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set Date
        run: echo "DATE=$(date -u '+%F')" >> $GITHUB_ENV
        
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "monalisa, cgallup, hubot"
          labels: "weekly sync, docs-team"
          title: "Team sync"
          body: |
            ### Agenda

            - [ ] Start the recording
            - [ ] Check-ins
            - [ ] Discussion points
            - [ ] Post the recording
                    
            ### Discussion Points
            Add things to discuss below

            - [Work this week](https://github.com/orgs/github/projects/3)
          pinned: false
          close-previous: false
        
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
